### PR TITLE
fix: remove reliance on opts.is_master

### PR DESCRIPTION
**Pull request by slawo**
Use box.cfg.read_only to decide when to instantiate the queue

### CODE REVIEW

**Comment by slawo** [comment]
Running some tests on an application which uses queues locally I ran into this error once `Prepare2pcError: Two-phase commit is locked`
I ran the test multiple times cleaning up the db folder each time and I do manage to reproduce it from time to time.

Should I remove the change in apply config?

Here is the complete log output from that run:

```
api_r1-1 | 2020-09-30 09:42:18.262 [43515] main/162/main twophase.lua:199 W> Updating config clusterwide...
api_r2-1 | 2020-09-30 09:42:18.262 [43523] main/133/lua twophase.lua:309 W> Prepared for config update at localhost:13301
api_r2-1 | 2020-09-30 09:42:18.262 [43523] main/133/lua twophase.lua:309 W> Prepared for config update at localhost:13302
api_r2-1 | 2020-09-30 09:42:18.262 [43523] main/133/lua twophase.lua:309 W> Prepared for config update at localhost:13303
api_r2-1 | 2020-09-30 09:42:18.262 [43523] main/133/lua twophase.lua:309 W> Prepared for config update at localhost:13304
api_r2-1 | 2020-09-30 09:42:18.262 [43523] main/133/lua twophase.lua:309 W> Prepared for config update at localhost:13305
api_r2-1 | 2020-09-30 09:42:18.262 [43523] main/133/lua twophase.lua:309 W> Prepared for config update at localhost:13306
api_r2-1 | 2020-09-30 09:42:18.262 [43523] main/133/lua twophase.lua:309 W> Prepared for config update at localhost:13307
api_r2-1 | 2020-09-30 09:42:18.262 [43523] main/133/lua twophase.lua:309 W> Prepared for config update at localhost:13308
api_r2-1 | 2020-09-30 09:42:18.262 [43523] main/133/lua twophase.lua:334 W> (2PC) Commit stage...
api_r1-1 | 2020-09-30 09:42:18.263 [43515] main/162/main twophase.lua:300 W> (2PC) Preparation stage...
api_r1-2 | 2020-09-30 09:42:18.263 [43519] main/137/lua twophase.lua:199 W> Updating config clusterwide...
storage_r2-1 | 2020-09-30 09:42:18.264 [43540] main/131/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r2-1 | stack traceback:
storage_r2-1 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r2-1 |  [C]: in function 'xpcall'
storage_r2-1 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r2-1 |  [C]: at 0x010c15c699
storage_r2-2 | 2020-09-30 09:42:18.264 [43546] main/135/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r2-2 | stack traceback:
storage_r2-2 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r2-2 |  [C]: in function 'xpcall'
storage_r2-2 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r2-2 |  [C]: at 0x0103bc7699
api_r2-1 | 2020-09-30 09:42:18.264 [43523] main/115/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
api_r2-1 | stack traceback:
api_r2-1 |      ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
api_r2-1 |      [C]: in function 'xpcall'
api_r2-1 |      ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
api_r2-1 |      [C]: at 0x0105ff6699
api_r2-2 | 2020-09-30 09:42:18.264 [43527] main/129/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
api_r2-2 | stack traceback:
api_r2-2 |      ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
api_r2-2 |      [C]: in function 'xpcall'
api_r2-2 |      ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
api_r2-2 |      [C]: at 0x0101b74699
api_r2-2 | 2020-09-30 09:42:18.265 [43527] main/137/lua twophase.lua:199 W> Updating config clusterwide...
storage_r1-1 | 2020-09-30 09:42:18.264 [43531] main/115/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r1-1 | stack traceback:
storage_r1-1 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r1-1 |  [C]: in function 'xpcall'
storage_r1-1 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r1-1 |  [C]: at 0x0105696699
storage_r1-2 | 2020-09-30 09:42:18.264 [43535] main/134/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r1-2 | stack traceback:
storage_r1-2 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r1-2 |  [C]: in function 'xpcall'
storage_r1-2 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r1-2 |  [C]: at 0x0100a7f699
api_r1-1 | 2020-09-30 09:42:18.265 [43515] main/198/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
api_r1-1 | stack traceback:
api_r1-1 |      ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
api_r1-1 |      [C]: in function 'xpcall'
api_r1-1 |      ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
api_r1-1 |      [C]: at 0x010fc2b699
api_r1-2 | 2020-09-30 09:42:18.265 [43519] main/137/lua twophase.lua:300 W> (2PC) Preparation stage...
storage_r1-1 | 2020-09-30 09:42:18.266 [43531] main/134/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r1-1 | stack traceback:
storage_r1-1 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r1-1 |  [C]: in function 'xpcall'
storage_r1-1 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r1-1 |  [C]: at 0x0105696699
storage_r1-2 | 2020-09-30 09:42:18.266 [43535] main/134/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r1-2 | stack traceback:
storage_r1-2 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r1-2 |  [C]: in function 'xpcall'
storage_r1-2 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r1-2 |  [C]: at 0x0100a7f699
storage_r2-2 | 2020-09-30 09:42:18.266 [43546] main/135/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r2-2 | stack traceback:
storage_r2-2 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r2-2 |  [C]: in function 'xpcall'
storage_r2-2 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r2-2 |  [C]: at 0x0103bc7699
storage_r2-1 | 2020-09-30 09:42:18.266 [43540] main/131/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r2-1 | stack traceback:
storage_r2-1 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r2-1 |  [C]: in function 'xpcall'
storage_r2-1 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r2-1 |  [C]: at 0x010c15c699
api_r1-2 | 2020-09-30 09:42:18.266 [43519] main/154/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
api_r1-2 | stack traceback:
api_r1-2 |      ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
api_r1-2 |      [C]: in function 'xpcall'
api_r1-2 |      ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
api_r1-2 |      [C]: at 0x010a940699
api_r2-1 | 2020-09-30 09:42:18.266 [43523] main/115/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
api_r2-1 | stack traceback:
api_r2-1 |      ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
api_r2-1 |      [C]: in function 'xpcall'
api_r2-1 |      ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
api_r2-1 |      [C]: at 0x0105ff6699
api_r2-2 | 2020-09-30 09:42:18.266 [43527] main/137/lua twophase.lua:300 W> (2PC) Preparation stage...
api_r1-2 | 2020-09-30 09:42:18.267 [43519] main/154/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
api_r1-2 | stack traceback:
api_r1-2 |      ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
api_r1-2 |      [C]: in function 'xpcall'
api_r1-2 |      ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
api_r1-2 |      [C]: at 0x010a940699
storage_r2-2 | 2020-09-30 09:42:18.268 [43546] main/135/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r2-2 | stack traceback:
storage_r2-2 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r2-2 |  [C]: in function 'xpcall'
storage_r2-2 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r2-2 |  [C]: at 0x0103bc7699
storage_r1-1 | 2020-09-30 09:42:18.268 [43531] main/134/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r1-1 | stack traceback:
storage_r1-1 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r1-1 |  [C]: in function 'xpcall'
storage_r1-1 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r1-1 |  [C]: at 0x0105696699
storage_r2-1 | 2020-09-30 09:42:18.268 [43540] main/131/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r2-1 | stack traceback:
storage_r2-1 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r2-1 |  [C]: in function 'xpcall'
storage_r2-1 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r2-1 |  [C]: at 0x010c15c699
storage_r1-2 | 2020-09-30 09:42:18.268 [43535] main/134/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
storage_r1-2 | stack traceback:
storage_r1-2 |  ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
storage_r1-2 |  [C]: in function 'xpcall'
storage_r1-2 |  ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
storage_r1-2 |  [C]: at 0x0100a7f699
api_r2-1 | 2020-09-30 09:42:18.268 [43523] main/115/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
api_r2-1 | stack traceback:
api_r2-1 |      ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
api_r2-1 |      [C]: in function 'xpcall'
api_r2-1 |      ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
api_r2-1 |      [C]: at 0x0105ff6699
api_r1-1 | 2020-09-30 09:42:18.268 [43515] main/198/main twophase.lua:63 W> Prepare2pcError: Two-phase commit is locked
api_r1-1 | stack traceback:
api_r1-1 |      ...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:62: in function <...rantoolapp/.rocks/share/tarantool/cartridge/twophase.lua:49>
api_r1-1 |      [C]: in function 'xpcall'
api_r1-1 |      ...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:148: in function <...l-cluster/tarantoolapp/.rocks/share/tarantool/errors.lua:132>
api_r1-1 |      [C]: at 0x010fc2b699
```

**Comment by akudiyar** [comment]
Yes, return back the is_master option in apply_config.

**Comment by slawo** [comment]
@akudiyar Actually after further investigation most of the issues steam from `cartridge.config_patch_clusterwide` called in `create_tube`.

In the vast majority of cases it fails during cluster startup when multiple nodes try to create the queue.
The only way I found to mitigate the issue is to retry calling `create_tube` and catching errors:

**Comment by akudiyar** [comment]
@slawo Seems that the issue is closed via #40, please check this

**Comment by sharonovd** [comment]
@slawo please feel free to reopen this PR or open another issue, if your problem is not solved via #40

**Pull request closed without merging**
